FROM node:latest

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .

ARG REACT_APP_SERVICE_ID
ARG REACT_APP_TEMPLATE_ID
ARG REACT_APP_USER_ID
ENV REACT_APP_SERVICE_ID=${REACT_APP_SERVICE_ID}
ENV REACT_APP_TEMPLATE_ID=${REACT_APP_TEMPLATE_ID}
ENV REACT_APP_USER_ID=${REACT_APP_USER_ID}

EXPOSE 8080

# Finally runs the application
CMD [ "npm", "start" ]
